[project]
name = "commercepivot"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "a2a-sdk[http-server]==1.1.0",
    "fastapi==0.115.0",
    "flagembedding==1.2.11",
    "httpx==0.28.1",
    "langchain==0.3.25",
    "langchain-core==0.3.58",
    "langchain-openai==0.3.16",
    "langgraph==0.3.0",
    "langgraph-checkpoint==2.0.25",
    "mcp[cli]==1.13.1",
    "numpy==1.26.4",
    "orjson==3.10.7",
    "pandas==2.2.3",
    "pydantic==2.11.4",
    "pydantic-settings>=2.5.2",
    "pymilvus==2.6.17",
    "milvus-lite==3.2.1",
    "pymysql==1.1.1",
    "python-dotenv==1.0.1",
    "python-multipart==0.0.9",
    "redis[hiredis]==5.1.0",
    "requests==2.32.3",
    "sentence-transformers==3.0.1",
    "setuptools>=80",
    "sqlalchemy==2.0.29",
    "sse-starlette==2.1.0",
    "structlog==24.4.0",
    "tenacity==8.5.0",
    "torch==2.4.0",
    "transformers==4.44.0",
    "uvicorn[standard]==0.31.1",
]

[project.scripts]
commercepivot = "commercepivot:main"

[[tool.uv.index]]
url = "https://pypi.tuna.tsinghua.edu.cn/simple"
default = true

[build-system]
requires = ["uv_build>=0.12.3,<0.13.0"]
build-backend = "uv_build"
